sudo: required
dist: trusty

language: node_js
node_js:
  - "0.12"

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb

install:
  - cd client
  - pwd
  - nvm install 6
  - npm install electron-builder@next
  - npm install -g ionic cordova
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run dist

notifications:
  slack: codeiain:L4zHgsi0hcrNA3s0r8WeuOWG
  
  