language: node_js
node_js:
  - "0.11"
  - "0.10"
env:
  - TEST_DIR=client
script: 
  - cd $TEST_DIR
  - npm install
  - ionic build browser
  - npm run-script electron dist
notifications:
  slack: codeiain:L4zHgsi0hcrNA3s0r8WeuOWG
  